description = "Ubi 8 base image with buildpacks for Node.js, Java, Quarkus and Procfile"

[[buildpacks]]
  uri = "docker://docker.io/paketocommunity/ubi-java-buildpack:0.1.1"
  version = "0.1.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/quarkus:0.4.0"
  version = "0.4.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:15.2.0"
  version = "15.2.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:3.0.2"
  version = "3.0.2"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.9.2"
  version = "5.9.2"

[[extensions]]
  id = "paketo-community/ubi-java-extension"
  uri = "docker://docker.io/paketocommunity/ubi-java-extension:0.2.0"
  version = "0.2.0"

[[extensions]]
  id = "paketo-community/ubi-nodejs-extension"
  uri = "docker://docker.io/paketocommunity/ubi-nodejs-extension:0.3.4"
  version = "0.3.4"

[lifecycle]
  version = "0.20.1"

[[order]]

  [[order.group]]
    id = "paketo-community/ubi-java-buildpack"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/quarkus"
    optional = true
    version = "0.4.0"

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "15.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "3.0.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.9.2"

[[order-extensions]]

  [[order-extensions.group]]
    id = "paketo-community/ubi-java-extension"
    version = "0.2.0"

  [[order-extensions.group]]
    id = "paketo-community/ubi-nodejs-extension"
    version = "0.3.4"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base:0.0.76"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:latest"
  run-image-mirrors = []
